apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: ${APP}
    env: ${ENV}
    app.openshift.io/runtime: ${APP}
    app.kubernetes.io/name: ${APP}
    app.kubernetes.io/part-of: ${APP}
    app.kubernetes.io/instance: ${APP}-${ENV}
    app.kubernetes.io/component: ${APP}-${ENV}
    app.openshift.io/runtime-version: ${ENV}
  name: ${APP}-${ENV}-config
data:
  application.properties: ${APPLICATION_PROPERTIES} 
  keystore_tomcat.jks: ${KEYSTORE_TOMCAT}
