apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${APP}
    env: ${ENV}
    app.openshift.io/runtime: ${APP}
    app.kubernetes.io/name: ${APP}
    app.kubernetes.io/part-of: ${APP}
    app.kubernetes.io/instance: ${APP}-${ENV}
    app.kubernetes.io/component: ${APP}-${ENV}
    app.openshift.io/runtime-version: ${ENV}
  name: ${APP}-${ENV}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: ${APP}
    env: ${ENV}
  sessionAffinity: None
  type: ClusterIP
  ClusterIP: None
status:
  loadBalancer: {}
